Import libraries that we will be using throughout the project

In [ ]:
import sys
import numpy as np
import matplotlib as mb


Manual computation of the output of a single neuron by doing weighted sum and adding bias to it

In [ ]:
input=[1.9,2.8,5.7]
weights=[4.8,2.9,8.9]
bias=5
output=input[0]*weights[0]+input[1]*weights[1]+input[2]*weights[2]+bias
print(output)

72.97


Manual computation of outputs of 3 neurons by doing weighted sum and adding bias to it

In [ ]:
input=[1.9,2.8,5.7]
weights1=[4.8,2.9,8.9]
weights2=[1.8,2.4,-0.7]
weights3=[4.9,-3.8,2.6]
bias1=5
bias2=2
bias3=3.5
output0=[input[0]*weights1[0]+input[1]*weights1[1]+input[2]*weights1[2]+bias1,input[0]*weights2[0]+input[1]*weights2[1]+input[2]*weights2[2]+bias2,input[0]*weights3[0]+input[1]*weights3[1]+input[2]*weights3[2]+bias3]
print(output)

72.97


Computation of outputs of multiple neurons by doing weighted sum and adding the bias to it

In [ ]:
input=[1.9,2.8,5.7]
weights=[[4.8,2.9,8.9],[1.8,2.4,-0.7],[4.9,-3.8,2.6]]
biases=[5,2,3.5]
output=[]
for nw,nb in zip(weights,biases):
  no=0
  for ni,weight in zip(input,nw):
    no+=ni*weight
  no+=nb
  output.append(no)
print(output)

[72.97, 8.15, 16.990000000000002]


Computation of output of single neuron using numpy library

In [ ]:
input=[1.9,2.8,5.7]
weights=[4.8,2.9,8.9]
bias=5
output=np.dot(weights,input)+bias
print(output)

72.97


Computation of output for multiple neurons using numpy library

In [ ]:
input=[1.9,2.8,5.7]
weights=[[4.8,2.9,8.9],[1.8,2.4,-0.7],[4.9,-3.8,2.6]]
biases=[5,2,3.5]
output=np.dot(weights,input)+biases
print(output)

[72.97  8.15 16.99]


Performing forward pass using 2 layer neural network by computing outputs of first layer and giving it as the input to the second layer

In [ ]:
input=[[1.9,2.8,5.7],[3.2,2.7,4.1],[5.1,7.6,5.9]]
weights=[[4.8,2.9,8.9],[1.8,2.4,-0.7],[4.9,-3.8,2.6]]
biases=[5,2,3.5]
layer1_output=np.dot(input,np.array(weights).T)+biases
layer2_output=np.dot(layer1_output,np.array(weights).T)+biases
print(layer2_output)

[[530.102 141.013 374.257]
 [522.699 132.006 328.134]
 [710.74  239.485 456.015]]


Performing forward and backward pass for a 2 layer neural network by using weights and biases to find output

In [ ]:
np.random.seed(0)
input=[[1.9,2.8,5.7],[3.2,2.7,4.1],[5.1,7.6,5.9]]
derival=[[0.5,-0.7],[0.9,0.7],[-0.2,0.5]]
class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights=0.1*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.input=inputs
    self.output=np.dot(inputs,self.weights)+self.biases
    return self.output
  def backward(self,derival,learning_rate=0.1):
    self.derweights=np.dot(np.array(self.input).T,derival)
    self.derbiases=np.sum(derival,axis=0,keepdims=True)
    self.derinputs=np.dot(derival,self.weights.T)
    self.weights-=learning_rate*self.derweights
    self.biases-=learning_rate*self.derbiases
    return self.derinputs
layer1=Layer_Dense(3,5)
layer2=Layer_Dense(5,2)
layer1.forward(input)
layer2.forward(layer1.output)
print(layer1.output)
print(layer2.output)
derinputs_layer2=layer2.backward(derival)
derinputs_layer1=layer1.backward(derinputs_layer2)
print(derinputs_layer1)

[[0.14363697 1.17099053 0.5773717  0.46622319 0.72280564]
 [0.35968959 0.98082632 0.58435518 0.73910349 0.89046408]
 [0.24192121 1.78416874 0.83313715 1.13619746 1.52638874]]
[[-0.091715    0.11507919]
 [-0.07580802  0.20126597]
 [-0.13870855  0.32397225]]
[[-0.04632126 -0.00428487 -0.00463244]
 [ 0.04281063 -0.00641022 -0.01147012]
 [ 0.03269257  0.00186015  0.00150145]]


Performing Rectified Linear Unit Activation to the first layer then performing back propagation

In [ ]:
input=[[1.9,2.8,5.7],[3.2,2.7,4.1],[5.1,7.6,5.9]]
output=[]
class Activation_ReLU:
  def forward(self,input):
    self.input=input
    self.output=np.maximum(0,input)
    return self.output
  def backward(self,derival):
    self.derinputs=derival.copy()
    self.derinputs[self.input<=0]=0
    return self.derinputs
layer1=Layer_Dense(3,5)
activation1=Activation_ReLU()
layer1_output=layer1.forward(input)
activation1_output=activation1.forward(layer1_output)
layer2=Layer_Dense(5,2)
layer2_output=layer2.forward(activation1_output)
print(activation1_output)
derival = np.random.randn(*layer2_output.shape)
derinputs_layer2=layer2.backward(derival)
derinputs_activation1=activation1.backward(derinputs_layer2)
derinputs_layer1=layer1.backward(derinputs_activation1)
print(derinputs_layer1)

[[0.         0.         0.07457515 0.22361335 0.        ]
 [0.         0.         0.09135187 0.60807927 0.        ]
 [0.         0.         0.         1.165757   0.        ]]
[[-0.00132609 -0.00260525  0.00176885]
 [ 0.00914065  0.00237804 -0.00267922]
 [ 0.06794844  0.0144805  -0.01796421]]


Computing normalised outputs by using softmax like activation function which is done by exponentiating the outputs and dividing it by row wise sums

In [ ]:
import math
layer_outputs=[[1.9,2.8,5.7],[3.2,2.7,4.1],[5.1,7.6,5.9]]
E=math.e
exp_values=np.exp(layer_outputs)
norm_values=exp_values/np.sum(layer_outputs,axis=1,keepdims=True)
print(norm_values)

[[  0.64287447   1.58121604  28.73725009]
 [  2.45325302   1.48797317   6.03402876]
 [  8.81838211 107.42988683  19.62567032]]


Performing forward pass using ReLU activation function then passing that layer to softmax activation function and then performing backpropagation

In [ ]:
input=[[1.9,2.8,5.7],[3.2,2.7,4.1],[5.1,7.6,5.9]]
class Activation_Softmax:
  def forward(self,inputs):
    exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
    probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output=probabilities
    return self.output
  def backward(self,derival,y_true):
    samples=len(derival)
    if len(y_true.shape)==2:
      y_true=np.argmax(y_true,axis=1)
    self.derinputs=derival.copy()
    self.derinputs=self.derinputs/samples
    return self.derinputs
dense1=Layer_Dense(3,4)
activation1=Activation_ReLU()
dense2=Layer_Dense(4,4)
activation2=Activation_Softmax()
dense1.forward(input)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output)
derinputs_layer2=layer2.backward(derival)
derinputs_layer1=layer1.backward(derinputs_layer2)
print(derinputs_layer1)

[[0.2517485  0.25039652 0.24426988 0.25358511]
 [0.25       0.25       0.25       0.25      ]
 [0.25       0.25       0.25       0.25      ]]
[[-0.00251854 -0.01012642 -0.00499521]
 [ 0.00138015  0.01151141  0.01048196]
 [ 0.00167118  0.00738862  0.00418387]]


Manual Computation of categorical cross entropy loss for a single prediction by summing the negative log of predicted probabilities weighted by target labels

In [ ]:
import math
softmax_output=[0.5,1.6,3.1]
target_output=[1,0,0]
loss=-(math.log(softmax_output[0])*target_output[0]+
       math.log(softmax_output[1])*target_output[1]+
       math.log(softmax_output[2])*target_output[2])
print(loss)

0.6931471805599453


Performing forward pass using ReLU for 1 layer and giving that as the input for the other layer that has softmax activation function the caluculating loss using categorical cross entropy and then performing backpropagation in a 2 layer neural network

In [ ]:
class Loss:
  def calculate(self,output,y):
    sample_losses=self.forward(output,y)
    data_loss=np.mean(sample_losses)
    return data_loss
class Loss_CategoricalCrossentropy(Loss):
  def forward(self,y_pred,y_true):
    samples=len(y_pred)
    y_pred_clipped=np.clip(y_pred,1e-7,1-1e-7)
    if len(y_true.shape)==1:
      correct_confidences=y_pred_clipped[range(samples),y_true]
    elif len(y_true.shape)==2:
      correct_confidences=np.sum(y_pred_clipped*y_true)
    negative_log_likelihood=-np.log(correct_confidences)
    return negative_log_likelihood
  def backward(self,y_pred,y_true):
    samples=len(y_pred)
    labels=len(y_pred[0])
    if len(y_true.shape)==1:
      y_true=np.eye(labels)[y_true]
    derinputs=(y_pred-y_true)/samples
    return derinputs
layer1=Layer_Dense(3,5)
activation1=Activation_ReLU()
layer2=Layer_Dense(5,2)
activation2=Activation_Softmax()
loss_function=Loss_CategoricalCrossentropy()
layer1_output=layer1.forward(input)
activation1_output=activation1.forward(layer1_output)
layer2_output=layer2.forward(activation1_output)
softmax_output=activation2.forward(layer2_output)
loss=loss_function.calculate(softmax_output,np.array(target_output))
derinputs_layer2=layer2.backward(derival)
derinputs_layer1=layer1.backward(derinputs_layer2)
print(derinputs_layer1)
print("Loss: ",loss)

[[-0.00569714 -0.00984347  0.00614529]
 [-0.00101791  0.0186918  -0.03925416]
 [ 0.00331566  0.00802423 -0.0081058 ]]
Loss:  0.6931003347205279


Performing forward pass using sigmoid function in a 2 layer neural network and then performing backpropagation

In [ ]:
class Activation_Sigmoid:
  def forward(self,input):
    self.inputs=input
    self.output=1/(1+np.exp(-input))
    return self.output
  def backward(self,derival):
    self.derinputs=derival*(self.output*(1-self.output))
    return self.derinputs
layer1=Layer_Dense(3,2)
activation1=Activation_Sigmoid()
layer1_output=layer1.forward(input)
activation1_output=activation1.forward(layer1_output)
layer2=Layer_Dense(2,2)
layer2_output=layer2.forward(activation1_output)
print(activation1_output)
derival = np.random.randn(*layer2_output.shape)
derinputs_layer2=layer2.backward(derival)
derinputs_activation1=activation1.backward(derinputs_layer2)
derinputs_layer1=layer1.backward(derinputs_activation1)
print(derinputs_layer1)

[[0.63654843 0.64625895]
 [0.65287816 0.60855061]
 [0.70812741 0.73597185]]
[[ 0.0001461   0.00074697  0.00068588]
 [-0.00159926  0.00025196 -0.00081147]
 [ 0.0020895  -0.00021386  0.00115185]]
